services:
  - type: web
    name: mautic
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MAUTIC_DB_HOST
        value: your-db-host.render.com
      - key: MAUTIC_DB_PORT
        value: 3306
      - key: MAUTIC_DB_NAME
        value: mautic
      - key: MAUTIC_DB_USER
        value: mauticuser
      - key: MAUTIC_DB_PASSWORD
        value: strongpassword
      - key: MAUTIC_RUN_CRON_JOBS
        value: "true"